"""Add payment_status constraint

Revision ID: 467d5ea65685
Revises: b73cec2db802
Create Date: 2025-08-05 13:06:57.686979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '467d5ea65685'
down_revision = 'b73cec2db802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add payment_status column with default 'Partial' and non-nullable constraint
    op.add_column('job', sa.Column('payment_status', sa.String(length=50), server_default='Partial', nullable=False))
    # Add check constraint for payment_status values
    op.create_check_constraint('check_payment_status', 'job', 'payment_status IN (\'Partial\', \'Completed\')')
    # Add order_tracking_id column
    op.add_column('job', sa.Column('order_tracking_id', sa.String(length=36), nullable=True))
    # Create index on payment_status
    op.create_index(op.f('ix_job_payment_status'), 'job', ['payment_status'], unique=False)
    # Adjust message table columns to allow nullable values
    op.alter_column('message', 'client_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('message', 'admin_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('message', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert message table columns to non-nullable
    op.alter_column('message', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message', 'admin_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('message', 'client_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # Drop index and columns from job table
    op.drop_index(op.f('ix_job_payment_status'), table_name='job')
    op.drop_constraint('check_payment_status', 'job', type_='check')
    op.drop_column('job', 'order_tracking_id')
    op.drop_column('job', 'payment_status')
    # ### end Alembic commands ###