"""Add recipient_id to Message model

Revision ID: 61749cd21965
Revises: c1ecbb04eb3f
Create Date: 2025-05-23 15:52:09.324520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61749cd21965'
down_revision = 'c1ecbb04eb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['recipient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'recipient_id')
    # ### end Alembic commands ###