"""Add client_deleted and admin_deleted to Message model and indexes

Revision ID: 8f2f1ab86b12
Revises: 61749cd21965
Create Date: 2025-05-23 21:01:56.004148
"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '8f2f1ab86b12'
down_revision = '61749cd21965'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_deadline'), 'job', ['deadline'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index(op.f('ix_job_user_id'), 'job', ['user_id'], unique=False)
    
    # Add columns with proper defaults and non-nullable constraints
    op.add_column('message', sa.Column('client_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('message', sa.Column('admin_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('message', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    
    # Update existing messages to set default values (in case any exist)
    op.execute("UPDATE message SET client_deleted = FALSE WHERE client_deleted IS NULL")
    op.execute("UPDATE message SET admin_deleted = FALSE WHERE admin_deleted IS NULL")
    op.execute("UPDATE message SET updated_at = NOW() WHERE updated_at IS NULL")
    
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_recipient_id'), 'message', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_message_sender_id'), 'message', ['sender_id'], unique=False)
    op.create_index(op.f('ix_reset_token_token'), 'reset_token', ['token'], unique=True)
    op.create_index(op.f('ix_reset_token_user_id'), 'reset_token', ['user_id'], unique=False)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_index(op.f('ix_reset_token_user_id'), table_name='reset_token')
    op.drop_index(op.f('ix_reset_token_token'), table_name='reset_token')
    op.drop_index(op.f('ix_message_sender_id'), table_name='message')
    op.drop_index(op.f('ix_message_recipient_id'), table_name='message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_column('message', 'updated_at')
    op.drop_column('message', 'admin_deleted')
    op.drop_column('message', 'client_deleted')
    op.drop_index(op.f('ix_job_user_id'), table_name='job')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_deadline'), table_name='job')
    # ### end Alembic commands ###