"""Add IPNRegistration table

Revision ID: b3b38fdd3fd3
Revises: 467d5ea65685
Create Date: 2025-08-07 13:56:31.317725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = 'b3b38fdd3fd3'
down_revision = '467d5ea65685'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipn_registration',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ipn_id', sa.String(length=36), nullable=False),
        sa.Column('url', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now()),
        sa.Column('ipn_status', sa.String(length=50), nullable=True, server_default='Active'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipn_registration_ipn_id'), 'ipn_registration', ['ipn_id'], unique=True)
    # Revert unintended nullable=True change for payment_status unless explicitly required
    op.alter_column('job', 'payment_status',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False,
                    existing_server_default=sa.text("'Partial'::character varying"))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'payment_status',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False,
                    existing_server_default=sa.text("'Partial'::character varying"))
    op.drop_index(op.f('ix_ipn_registration_ipn_id'), table_name='ipn_registration')
    op.drop_table('ipn_registration')
    # ### end Alembic commands ###